### ISSUE TITLE
No ability to specify which qubits used in Qiskit transpiler

### ISSUE THREAD

**Issue by nonhermitian** [SRI-International/QC-App-Oriented-Benchmarks#8]
The benchmarking suite has no way to specify which qubits are used in the execution of a given circuit, i.e. one cannot define an `initial_layout` here:

https://github.com/SRI-International/QC-App-Oriented-Benchmarks/blob/5e1f68eed96d667b9bcc08d3b04b2004f4c04643/_common/qiskit/execute.py#L269

This is nice to have because, for example, in Fig. 11 of https://arxiv.org/abs/2110.03137 you look at dynamic Berstein-Vazirani on the Lagos system, but the 0-1 edge of the coupling map is actually not the best (it is also not the worst).  On that machine the 3-5 edge is the best in terms of fidelity:

```
[3, 5] 0.7861328125
[2, 1] 0.77197265625
[5, 4] 0.7678222656250001
[5, 3] 0.7481689453125
[3, 1] 0.7360839843750001
[4, 5] 0.7303466796875
[0, 1] 0.7076416015625001
[1, 2] 0.665771484375
[6, 5] 0.64208984375
[1, 0] 0.6323242187500001
[1, 3] 0.6124267578125001
[5, 6] 0.5809326171875001
```

**Comment by rtvuser1** [comment]
If we use the option mentioned about when executing the benchmarks on casablanca, we do see slightly improved performance for the circuits with width > 4.

    optimization_level=3, layout_method='sabre', routing_method='sabre'

This is the results shown in the paper without the options set:
![_ALL-vplot-2](https://user-images.githubusercontent.com/13694426/139558266-de0609f5-71cc-40e3-a340-af160562f065.jpg)

and here is the result with the options set:
![_ALL-vplot-2](https://user-images.githubusercontent.com/13694426/139558309-c5875e86-f228-4b66-aad9-8acbf679d9f9.jpg)

Two questions ... 

1) should this be the default for executing on ANY of the IBM hardware services?
If so, then the options could be set by default in the execute.py module.
If not, then we'd have to expose a mechanism to configure options along with the backend selection.

2) Would we achieve better results if we provided specific mappings for each benchmark circuit, rather than use the 'sabre' approach?  Are there options that would provide even better results?

**Comment by nonhermitian** [comment]
Hmm, the layout method not being valid is odd.  Will take a look.

1. I would say yes.  In particular see here: https://nonhermitian.org/posts/2021/2021-10-31-best_swap_mapper_qiskit.html

2.  I think the manual setting would be a bit cheating.  It should be all software based, but a best faith effort to pick the best SW options.

**Comment by rtvuser1** [comment]
Running on guadalupe also show better results using these options:

Without the options:

![_ALL-vplot-2](https://user-images.githubusercontent.com/13694426/139593331-5ff6bd71-a720-4044-9e35-c9a237d1f102.jpg)

With the options set:

![_ALL-vplot-2-opt3-sabre](https://user-images.githubusercontent.com/13694426/139593357-c4389dea-7a1a-469e-9019-8611f40e6da4.jpg)

The code has been now modified to set these options by default for all IBM hardware backends.

I will keep this issue open for now, so users can follow the trail of this change and because two issues still remain here:

1) Even though the options seem to take effect and do provide better fidelity results, the error message still appears. Perhaps this is a Qiskit version issue:

     UserWarning: routing_method is not a recognized runtime option and may be ignored by the backend.

2) We should provide a mechanism to override the default options in case users would like to experiment with other options.  That change has not been made yet.

**Comment by nonhermitian** [comment]
I have raised an issue here: https://github.com/Qiskit/qiskit-terra/issues/7200

However, `execute` is out of favor and execution of circuit should be done via two steps:

```python

trans_qc = transpile(qc, backend, optimization_level=3,
                     routing_method='sabre', layout_method='sabre')

job = backend.run(trans_qc)
```
This does not raise the warning.

**Comment by rtvuser1** [comment]
The above change has been made to avoid the errors on execution.
In addition, the IBM-specific code has been removed from the execute.py module, by passing an 'exec_options' object when calling set_execution_target.
This object contains 3 fields: optimization_level, layout_method routing_method, which if provided will be passed to the tranpile method.
The exec_options parameter is surfaced in all the benchmarks and may be set by the user in the first cell of the Jupyter Notebook.  It is defaulted to the recommended IBM options in the body of code the user uncomments to select an IBM device.
This makes the underlying execute.py method hardware-agnostic.
 
Blake Johnson of IBM has described another mechanism for additional optimization in:

   https://gist.github.com/blakejohnson/9d0d7aa8c50350f869ed3eeca185f8f0

This Issue will remain open until a method for users to supply the custom pass manager for additional performance gains.

**Comment by rtvuser1** [comment]
@nonhermitian @blakejohnson The 'develop' branch now contains a method to enable the pass manager as described above. The Jupyter notebook temple adds one new cell to define a pass manager and add it to the exec_options object, as a callback executed in the execute.py module. Needs review before merging to staging.

**Comment by rtvuser1** [comment]
This issue closed ... the exec_options variable was added to the execute_method so that user can select optimization_level, layout_method, and routing_method for execution.
The 'transfomer' field can also be set to enable the execution of a circuit transformer() function that is called after the above options are passed to transpiler, but before the run(0 method is invoked.
